### ISSUE TITLE
demo: "special" symbols get highlighted

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#128]
Javascript keywords like in, instanceof, true, null and undefined get highlighted green/blue even when in reality they are just normal symbols.

**Comment by jiggzson** [comment]
You really put this bad boy through the wringer! Thanks! I really appreciate it. This issue is a Codemirror thing. All I really want from it is the bracket completion and bracket highlighter but I'm forced to use a highlight package if I want bracket highlighting. I'll revisit this since I was sort of in a rush the last time.
