### ISSUE TITLE
Comparison operators are weird

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#133]
They return the Boolean value true when true and 0 when false! This makes evaluate() after nerdamer() immediately throw for true because Boolean does not have an evaluate method.

**Comment by Happypig375** [comment]
Ok I might be wrong here, it is trying to call text() as stated in the error message.

**Comment by jiggzson** [comment]
What type of expression did you have in mind? One for TRUE and zero for FALSE? It's interesting that you discovered this because I don't even have this documented. This an concept I'm playing around with for future releases. I'm open to suggestions since I'm not really married to any particular construct for this.

**Comment by Happypig375** [comment]
>One for TRUE and zero for FALSE?

Well, my calculator does this.

**Comment by Happypig375** [comment]
Thanks for fixing!
