### ISSUE TITLE
median(r,r,r,r) won't evaluate

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#136]
mean(r,r,r,r) => r (OK)
mode(r,r,r,r) => r (OK)
median(r,r,r,r) => median(r,r,r,r) (What?)

When the arguments are the same value, it should just return it.

**Comment by jiggzson** [comment]
Not completely true. What is r is Infinity?

**Comment by Happypig375** [comment]
The median of a bunch of Infinities is still Infinity, unless I'm mistaken.

**Comment by jiggzson** [comment]
Nope. For example:
**a = Infinity
b = Infinity + 1 = Infinity
a =/= b**
I typed this example in Wolfram Alpha and it also considers this undefined.

**Comment by Happypig375** [comment]
(Relates this to #134)

**Comment by jiggzson** [comment]
I'm beginning to think that you might be right on this issue. After thinking about this a bit, my example does not apply since r = r so all Infinities are equal. I still don't understand why Wolfram Alpha (W.A.) is returning undefined on this one. Interestingly it returns x for max(x,x). I'll mimic W.A.'s behavior but I'll research this a bit more.

**Comment by Happypig375** [comment]
Huh, another Wolfram Alpha bug? I discovered one earlier...
https://github.com/jiggzson/nerdamer/blob/e29df34809fa6f6591c9462ecbb57692e99c6809/spec/core.spec.js#L124
I thought Wolfram Alpha, being a paid product, should not have these kinds of bugs...

**Comment by jiggzson** [comment]
Any update on this one? If not let's just stick to the current implementation and close this one.

**Comment by Happypig375** [comment]
Eh, I will trust Wolfram Alpha on this one even though I have doubts. Ok. Closing.
