### ISSUE TITLE
Documentation: nerdamer.getCore

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#140]
It returns the core object, but the core object is not documented...?

**Comment by jiggzson** [comment]
The core is a large object. It's basically nerdamer. Documenting it is a tremendous undertaking. I would love to at some point since it has some very useful functions. The other issue is that in order for the many of the functions to be used directly the user, the user would need to understand the logic behind the groups. This is a model I devised for quickly collapsing objects. Since JavaScript doesn't allow operator overloading, the String data type serves as a go-between for objects and the grouping makes looking and simplification fast and simple. The downside is that it deviates from the standard model of fields and rings.

**Comment by ljacqu** [comment]
One question here, is the core object something a typical user should know about and will come in contact with?

**Comment by jiggzson** [comment]
@ljacqu quite honestly no. You would only need it when extending nerdamer or when you need more control. Certain operations demand more control such as creating custom operators but this has only come up very few times.

**Comment by jiggzson** [comment]
@Happypig375 Are we in agreeance that documenting this is completely unnecessary? 99.999% of the user of the library will never have need of the core and the source code has documentation if they ever need to know. Let me know if you agree so we can close this one.

**Comment by Happypig375** [comment]
I could think of another reason to not document the core object: It changes with every release. And  documenting it means the documentation gets outdated frequently. Right?
