### ISSUE TITLE
You can only set but not get

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#147]
There is setConstant but no getConstant
There is set (option) but no get (option)
There is setFunction but no getFunction
There is register but no unregister
What??

**Comment by jiggzson** [comment]
I'm lost here. You may have to explain this one a bit more. Constants are automatically used when set. Same with setFunction. The register is sort of like declaring a function but on a more global level. Why unregister? Just override it.

**Comment by Happypig375** [comment]
I mean, you can set something to a value but not get the value back. You should be able to get the value back after you have set it.

**Comment by jiggzson** [comment]
I think there's confusion due to the naming of the methods. I don't think you'd be asking about a getFunction if it was called declareFunction instead of setFunction. Same goes for register. I've added a getConstant method and a get method since that makes sense. I definitely wouldn't want to add a getFunction method since this would give the impression that the person is getting back a function and this is by no means how the library is set up.

**Comment by Happypig375** [comment]
Okay.
Probably need more documentation to specify this.

**Comment by jiggzson** [comment]
@Happypig375 noted. I'll make a note under #141. This should also include me making a note of all options for nerdamer.set if I haven't already mentioned this in another issue. I'll start working on a list.
