### ISSUE TITLE
Better big number support

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#221]
After #196 is implemented, it would make sense to do the same thing to decimals too. I propose a new parameter for text: Precision (number of digits after decimal point). For example: nerdamer('pi').text(24) or nerdamer('pi').text('decimals', 24) would return 3.141592653589793238462643. An alternative would be the number of significant figures in place of number of digits after decimal point. Calling text function with 'fractions' as first parameter will have no effect on the result. An alternative to this would be limiting the number of digits of the numerators and the denominators to the number provided. If this parameter is not specified/is undefined, it would keep the old behaviour. Question to consider: nerdamer('1.00001').text(3) returns 1 or 1.000? (I prefer the latter because it clearly specifies that it is not precise)

**Comment by Happypig375** [comment]
Maybe the internal representation can use infinite series.
As far as I can remember,
almost all current nerdamer functions and constants can be represented as infinite series.
I don't remember any scenario where infinite series cannot be used to represent values.

However, this would require #134 to be implemented and sum to be moved from Calculus.js into core.js.
What do you think?

**Comment by jiggzson** [comment]
>As far as I can remember,
almost all current nerdamer functions and constants can be represented as infinite series.

@Happypig375, correct and at some point we won't have a choice but to do so. At present some functions are already calculated in this fashion, The functions are housed in the **`Math2`** object. The catch is that because the **`Frac`** class uses a ratio of two big integers, it gets really precise. I mean "really unbelievably **huge** numerators and denominators" precise. The [current toDecimal](https://github.com/jiggzson/nerdamer/blob/79c90333e25377d9c1e8ab1d9be7f1d0f728e930/nerdamer.core.js#L1780) implementation relies on JavaScript division and as such is a major source of grief. So to find a usable middle I created 
 this [toDecimal](https://github.com/jiggzson/nerdamer/blob/cd66a98105e62bb6f10f17036bd922357540a4ad/nerdamer.core.js#L1791) method which does the long division up to some precision. Currently it needs slightly more polish and some tests are going to needed to be updated to reflect this increase in precision.

>However, this would require #134 to be implemented and sum to be moved from Calculus.js into core.js.

Infinity is mostly implemented, it's missing pow I think, and the cleanest way to do this is to just make them a group. This way we can anticipate them anywhere in the code and the checks for them will be fast. This means that I'll be removing the existing implementation and redoing it in the proposed way.  I was hesitant about supporting `undefined` but this becomes really simple to deal with once undefined just converts anything to undefined in any operation (Hopefully I don't have to eat my words some day 😆).

**Comment by jiggzson** [comment]
@Happypig375, Let's discuss big numbers here.

**Comment by Happypig375** [comment]
Cross-link: https://github.com/jiggzson/nerdamer/issues/358#issuecomment-359143708

**Comment by jiggzson** [comment]
@Happypig375, this seems to be a repeating issue. It's clear that nerdamer needs better BigNumber support and this issue is being worked on. It just seems to be spread over multiple issues. I'm moving this issue to #404 and all other issues related to BigNumber support.
