### ISSUE TITLE
how can I use 

### ISSUE THREAD

**Issue by umaiuma** [jiggzson/nerdamer#231]
There is 'log' function but, there is not 'ln' function. How can I use it?

**Comment by jiggzson** [comment]
I'm sorry but I don't understand what you're asking.

**Comment by Happypig375** [comment]
@umaiuma You need to understand the difference between mathematical context and computational context.
In Mathematics, log is base 10. In computers, log is base e. So, the ln function, aka the log function with base e, is log. The log function in Mathematics is log10 here.

**Comment by Happypig375** [comment]
Adding the ln function as a synonym to log would be this: `nerdamer.setFunction('ln', 'x', 'log(x)');`
@jiggzson, consider adding this to nerdamer?

**Comment by jiggzson** [comment]
I'm all on board but the **lb** function but adding a synonym for **log** is not that simple since much of the library is committed to **log**. If I create an alias for **ln** to be log then what happens with **ln(x)+integrate(1/x, x)**? Creating a setting isn't a simple solution either since **log** is a core function embedded deep within the library.

**Comment by jiggzson** [comment]
The lb function can be used by specifying the base with the log function. I'm going to avoid using this as this might conflict with the future plan for units.
