### ISSUE TITLE
setVar prevents implicit number multiplication

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#257]
@master
```js
nerdamer.setVar('π', 'pi');
nerdamer('π'); //=> pi
nerdamer('ππ'); //=> ππ
nerdamer('3π'); //Error: 3π is not a valid variable name
```

**Comment by Happypig375** [comment]
@dev Same as @master but no need to have `nerdamer.setVar('π', 'pi');`

**Comment by jiggzson** [comment]
@Happypig375 . The problem is that you're creating all sorts of conflicts. In issue #135 you ask for nerdamer to recognize 'π' as 'pi' yet here you're asking to override it. Hopefully you chose 'π' just as an example. 'ππ' is recognized as a variable name if you want it to recognize it as 'π*π' then use the setting as specified in issue #229

**Comment by jiggzson** [comment]
This should be fixed
