### ISSUE TITLE
setFunction does not substitute values properly

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#282]
```js
nerdamer.setFunction('lcm', ['a', 'b'], '(a / gcd(a, b)) * b');
nerdamer('lcm(3,x)') //b
```
Isn't b a parameter? I have supplied it (x), yet it still returns b.

**Comment by Happypig375** [comment]
Also related:
(Using current dev branch)
lcm(3,x) => x
lcm(3,2) => 6 (this is not equal to 2 XD)

**Comment by jiggzson** [comment]
The problem is that gcd(3,x) returns 3 :disappointed:

**Comment by jiggzson** [comment]
When parsing an expression nerdamer creates a subs object and uses that to substitute in known values. The problem was that when setFunction was called, the first subs object was created. However when lcm was called it created a second subs object but that subs object was never passed off which caused it to use the first subs object. Fixed. Might be related to #212.

**Comment by jiggzson** [comment]
@Happypig375 Special thanks for this one. This was an awesome catch.
