### ISSUE TITLE
Use different math functions?

### ISSUE THREAD

**Issue by jonathanmarvens** [jiggzson/nerdamer#304]
Hi, @jiggzson!

First of all, __thank you so much__ for this __*awesome*__ library. (Please LMK how I can buy you a beer!)

Here’s my situation: I’m using this library for a project in which I’d like to use a different `BigInteger` library and different math functions for the solver. I’m aware that I’m able to provide my own functions to the core and also replace existing ones, but what I’d like to know is what are *all* the functions I’d need to replace via `nerdamer.register` to accomplish this successfully without breaking *any* functionality in the library? I’m not trying to change the higher-level algorithms, but just the core math functions used to implement all the different algorithms. Hopefully that makes sense?

Also, another question: How are floating-point calculations handled in the library?

Thanks in advance for your help!

\- *Jonathan*

__P.S.__ *Seriously*, please LMK how I can buy you a beer 🙂!

**Comment by jiggzson** [comment]
Thanks @jonathanmarvens. Thanks for the offer of the beer. I haven't had a chance to set up an organization but I'll try to get to that as some point. As far as using a different BigInteger library, nerdamer currently uses [this](https://github.com/peterolson/BigInteger.js) BigInteger library. I guess if the API is identical then I see no reason why you can't swap it out. The unfortunate thing is that you have to replace it in the source code. I'll keep this issue in mind for future designs.

To get all the functions within nerdamer you get do this
```javascript
var core = nerdamer.getCore();
console.log(core.PARSER.functions)
```
This will list all the functions. This issue might be related to #248 which is one of the major issues that I'm tackling. One possibility might be to just override the function manually. So for instance if you want to modify the behavior of sine you could do
```javascript
var core = nerdamer.getCore();
var functions = core.PARSER.functions;
var sin = functions.sin[0]; //store the original sine function
functions.sin[0] = function(a) {
    //the original behavior goes here
    if(a.equals('pi'))
        return sin(a);
    //the modified behavior goes here
    return new core.Symbol(6);
}
```
As for floating point calculations, this is done by first converting to a fraction and then working with fractions until you want it back. The loss of precision is calculated and if it finds any then it just uses a fraction with a base 10 denominator. So the actually calculations aren't done in floating point but with fractions. Given 0.1+0.2 the library convert to 1/10+2/10. For pi it would just do (nth digit of pi)/(10^n) since I'd be doing the calculations with that precision anyway. I hope that makes sense.

**Comment by Happypig375** [comment]
@jonathanmarvens
See #248 for a new, modern and simple solution

**Comment by jiggzson** [comment]
@jonathanmarvens, were any of the solutions provided above helpful?
