### ISSUE TITLE
Cannot differentiate some functions

### ISSUE THREAD

**Issue by AnatolyShirykalov** [jiggzson/nerdamer#339]
Actual for Nerdamer 0.7.11.
I have just noticed a very strange result of differentiating:
```javascript
console.log(nerdamer.diff('atan(e^x)').text()); // => ((119696244^(-x)*325368125^x)^2+1)^(-1)*e^x
```
But we can see normal behavior here:
```javascript
console.log(nerdamer.diff('e^x').text()); // =>e^x
console.log(nerdamer.diff('atan(x)').text()); // => (1+x^2)^(-1)
```

**Comment by jiggzson** [comment]
@AnatolyShirykalov the reason this is happening is because the evaluate method is called automatically when calling diff this way. Basically
```javascript
var x = nerdamer.diff('atan(e^x)');
```
is the similar to _(but not exactly the same thing as)_ calling
```javascript
var x = nerdamer('diff(atan(e^x),x)').evaluate();
```
I believe what you're looking for is 
```javascript
var x = nerdamer('diff(atan(e^x),x)');
//(1+e^(2*x))^(-1)*e^x
```
which will give you the purely differentiated function. I am however noticing that e^x was never evaluated. Is that what you were referring to instead?

**Comment by AnatolyShirykalov** [comment]
@jiggzson Thank you! That is exactly what I need.

**Comment by jiggzson** [comment]
No problem.
