### ISSUE TITLE
Symbolic output for min and max

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#348]
See https://github.com/jiggzson/nerdamer/issues/279#issuecomment-346048134

**Comment by jiggzson** [comment]
Cool. I'll give it a go soon.

**Comment by jiggzson** [comment]
Two things.
1. This will be an optional setting. I don't mind implementing this but I do mind making this the default behavior especially given the way this is being suggested. If I'm to make this the default behavior I may have to implement something like [this](https://gist.github.com/jiggzson/f41fcbd5a0bc385d1211bd8d6f3678df) for min and max. It's actually faster than Math.min.apply in quite a few environments that I tested. If you're ever interested in testing it a bit more then I'll do all the changes as once.
2. What happens when we have something like max(0, cos(pi/2), 4)? The min is zero but which one since cos(pi/2) = 0?

**Comment by Happypig375** [comment]
Hmmm. Valid concerns. Let me dig into this a little more.

Oh, Wolfram Alpha has a formula for min: min(a, b) = 1/2 a sgn(b - a) + 1/2 b sgn(a - b) + a/2 + b/2

Also for max: max(a, b) = 1/2 a sign(a - b) + 1/2 b sign(b - a) + a/2 + b/2

(Note: Only real inputs are defined.)

No ambiguity yeah!

However, it is possibly significantly slower than your implementation above. Any thoughts?

**Comment by jiggzson** [comment]
@Happypig375, I addressed this issue but right now it requires yet another setting :disappointed:. It does add a bit of overhead but it's acceptable so I'm not opposed to making this the default behavior. I'd like to test it a bit more before I do so. If you have the time that would be awesome if not the way to achieve this for the time being is
```javascript
nerdamer.set('SYMBOLIC_MIN_MAX', true)
var x = nerdamer('min(cos(2), pi, 11)'); // cos(2)
```
I'd venture to say that this would be the preferred behavior overall since:

```javascript
nerdamer.set('SYMBOLIC_MIN_MAX', true);
var x = nerdamer('min(cos(2), pi, 11)-cos(2)'); // 0
```
No rounding errors.
