### ISSUE TITLE
Symbol replacement applied to outside of the function

### ISSUE THREAD

**Issue by yosuke** [jiggzson/nerdamer#349]
Example to reproduce the problem
```
nerdamer.setFunction('f', ['x', 'y'], 'x^2+y');
var x = nerdamer('f(4, 7)+x+y').toString();
console.log(x.toString());
```
What I expect is
```
23+x+y
```
But I get
```
34
```

**Comment by jiggzson** [comment]
@yosuke, this issue is related to #282 and has been fixed in the dev branch so if you need this issue fixed right away it's availabe. I'm currently wrapping up some minor issues on the dev branch and I'll be merging this branch to master and subsequently publishing to npm.  I just checked this and it does give the output you expect.

**Comment by yosuke** [comment]
@jiggzson, thank you for the quick reply (and thank you again for the great software).
Confirmed expected behavior by checking out the dev branch.

**Comment by jiggzson** [comment]
@yosuke, no problem and thank you.
