### ISSUE TITLE
Undocumented .eq method doesn't work with square-roots

### ISSUE THREAD

**Issue by peey** [jiggzson/nerdamer#351]
Hey, I found the method `.eq` on the object created by doing `nerdamer(...)`, but quickly realized that it does not work every-time.

For example, I was expecting the following to be true : 

```js
a = nerdamer("sqrt(2)")
b = nerdamer("sqrt(2)")
a.eq(b) // expected this to be true, but was false
```

Turns out, the implementations of `eq, lt, gt, gte, lte` in [nerdamer.core.js](https://github.com/jiggzson/nerdamer/blob/79c90333e25377d9c1e8ab1d9be7f1d0f728e930/nerdamer.core.js#L1597) work only with constant values. 

Maybe it doesn't work because the `isConstant()` on those lines doesn't recognize "sqrt(2)" as a constant. 

I'm currently checking for equality between two objects by simply doing `a.subtract(b)` and checking if that is equal to 0 or not.

**Comment by jiggzson** [comment]
@peey, you are correct. The default behavior does not check for constants in functions. The **`isConstant`** calls for those functions have to be updated and need to be be called with `true` as the first argument. If you update the eq function to this: 
```javascript
      eq: function(value) {
            value = _.parse(value);
            if(this.symbol.isConstant(true) && value.isConstant(true))
                return this.symbol.equals(_.parse(value));
            return false;
        },
```
then it will return true for your example. I'll update this on the dev branch with the next commit.

Thanks.

**Comment by Happypig375** [comment]
`nerdamer("x").eq(nerdamer("x")) will be true when the subtracting method is used, but not const check then compare method.
This should be intended, right? Just checking.

**Comment by jiggzson** [comment]
@Happypig375, I'm guessing you're worried about saying that Infinity = Infinity or something that's not guaranteed to be true right? I popped this into Wolfram Alpha and ironically it returns true for a=a. I guess the assumption must be that a is real.

**Comment by Happypig375** [comment]
Let me double check:
Infinity=Infinity

Result:
True

Ok, nothing unusual here.

**Comment by jiggzson** [comment]
So I'm guessing that we never had a problem before when Infinity-Infinity=0. Good to know. Makes everything a lot easier.

**Comment by Happypig375** [comment]
But Infinity-Infinity is not defined
While Infinity=Infinity.

We can't say something like
Infinity+1=Infinity
Subtract Infinity from both sides
1=0

**Comment by jiggzson** [comment]
@Happypig375, precisely my point. It's strange that Wolfram Alpha returns true for infinity=infinity. Since this is undefined we can't say for sure that this is true. That means that @peey method should work, and maybe more efficiently, even for infinity=infinity given that we assumed all variables to be real or better yet complex.

**Comment by Happypig375** [comment]
>Since this is undefined we can't say for sure that this is true.

I am starting to think in terms of extended reals and cardinals.
Ok, so Infinity is an element of the set of extended reals (this set should be added into #350), which defines operations of Infinity.
Infinity=Infinity is true because well, they are equal!
It is the same as Infinity+1=Infinity is true, so is Infinity*2=Infinity*3...
But when we do Infinity-Infinity, it can equal to any number, since
Infinity+x=Infinity, where x in {R} and x <> 0
Infinity+x-Infinity=Infinity-Infinity
If Infinity-Infinity=0,
x=0
However, we assumed that x <> 0
Contradiction

Cardinals are another concept, different from the extended reals. I will not cover them here.

>given that we assumed all variables to be real or better yet complex.

Even better, extended complex numbers! (See Riemann sphere, also TBA into #350)

A solution: Infinity should be special-cased and be operated on in a different way.

**Comment by jiggzson** [comment]
@peey, a fix for this was added in v0.7.15. Did that solve your issue?

**Comment by peey** [comment]
Yes, v0.7.15 solves my original issue - `.eq` works. And I also tested that `.lt` and `.gt` work too.

However, I tested `.gte` and `.lte` and they still give errors, namely that `this.greaterThan` and `this.lessThan` are not defined:

```
> a = nerdamer("sqrt(2)")
> b = nerdamer("sqrt(2)")
> c = nerdamer("sqrt(3)")

> c.gte(a)
TypeError: this.greaterThan is not a function
    at Expression.gte (/media/peey/software/peey/experiments/node_modules/nerdamer/nerdamer.core.js:1680:25)
    at repl:1:3

> c.lte(a)
TypeError: this.lessThan is not a function
    at Expression.lte (/media/peey/software/peey/experiments/node_modules/nerdamer/nerdamer.core.js:1683:25)
    at repl:1:3

```

In addition to this, I ran some tests to verify if `.lt` and `.gt` are working correctly. You may use them to add to the unit testing spec if needed:

```
> a = nerdamer("2sqrt(5)")
> c = nerdamer("sqrt(13)")
> d = nerdamer("sqrt(21)")
> e = nerdamer("sqrt(20)")
> f = nerdamer("sqrt(5) + sqrt(3)")
> g = nerdamer("sqrt(5) + sqrt(7)")
> a.lt(g)
true
> a.lt(f)
false
> a.gt(c)
true
> a.gt(d)
false
> a.gt(e)
false
> a.lt(e)
false
> a.eq(e)
true
```

**Comment by jiggzson** [comment]
I'll fix gte and lte. Thanks for the tests.

**Comment by jiggzson** [comment]
The tests were added. Closing.
