### ISSUE TITLE
Improve rounding and large numbers

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#357]
By rounding, I do not mean round(), but rather rounding errors.
Rounding errors hurt numeric accuracy and especially become obvious when the input numbers are large.

For example:

In/Out:  from Demo, all three options checked, version 0.7.15
Expected: from Wolfram Alpha

In|Out|Expected
-|-|-
sinc(π)|3.898171832519376e−17|0
sin((20!-1)pi)|−0.9986151560496079|0
sin(20!-1)|0.4012031156704558|-0.554007294695142101...
700!!|Infinity|283447544216993144778074714203109965106294288578534497881773812022440208304015979886370251743269961774921956862417919779448698101927968285625882207647224727885803963336565170736782175994989805980002318070942996401197741301432409606189826546584224321800169809017381408660433002007623266070629715646678019366818116686834126573080715057701348534760064907215819244265362786656637176081560635359006262390703929714914097914220281054994349911244606381936842782206871126400597252658313788141032128632801217958458132892318258703144565743461659755151170884023677947455508496762922566806372688858287583460621618444790892983808754620510546796859225403164533656327730678445046933316734113406119896336674084411550836986714280834039889700417805415577538131495285522774674636800000000000000000000000000000000000000000000000000000000000000000000000000000000000000

A lot of this come down to the fact that a lot of nerdamer functions are implemented using JavaScript arithmetic, e.g. trig functions with real input, but JavaScript arithmetic are prone to rounding errors and have no support for numbers larger than 1.7976...e308.
A decision has to be made here:

1. Keep using JavaScript arithmetic
Pro: Fast
Con: Rounding errors
2. Implement with parser operations and infinite series
Pro: Precision for integers
Con: Slow
3. Wait until #221 is fully implemented
Pro: Precision for both integers and decimals & speed
Con: Long waiting time

Any thoughts?

**Comment by jiggzson** [comment]
Rounding errors and large numbers present a special challenge. The first is, as I may have mentioned before, that nerdamer stores numbers as a fraction of integers which can cause both the numerator and denominator to get ridiculously large. There are ways to mitigate this but all have a price. One way will be #221.

Issues like #269 are unacceptable and need to be fixed but 700! doesn't really bother me at all. If you're doing that kind of math with JavaScript you honestly just picked the wrong tool. You're better off going the route of using some CAS back-end. From all of the projects I've noticed so far, I get the impression that most people are using it as a tutoring/teaching aid, small engineering/robotics, or just a school project. Not only that but since this library runs in the browser, environments vary greatly.

Issues like this takes away time from  getting integrate, divide, factor, etc to be more complete. IMHO it would be time better spent since JavaScript is maturing and hopefully will add better support for numbers in the near future. 

It would however be helpful to detect known values (other their patterns) of the input for functions as in sine, cos, etc return based  on those  values. This would not only speed things up but would eliminate some rounding errors. I would greatly appreciate help with such a list.

Eventually I'll have to use a cocktail of the solutions you mentioned above but I'm not quite there yet.

**Comment by Happypig375** [comment]
So I guess the picked option is 3. Ok.

**Comment by jiggzson** [comment]
Yes. Three is the leading candidate since so far it's shown the be the most efficient but the others might still come in handy. Yes sinc(π)<>0 is very much still and issue and I'd like to just detect and return 0 based on the input being π. Having looked at other math packages and read several math algorithms, this approach is not uncommon at all. Why calculate something if you already know the answer? It's efficient and fast.

**Comment by jiggzson** [comment]
As addendum to above: This is what I meant by compiling a list of known values.

**Comment by Happypig375** [comment]
A list of known values...
I am thinking of adding the rest of the values of trigonometric constants [in here](https://en.wikipedia.org/wiki/Trigonometric_constants_expressed_in_real_radicals?wprov=sfla1).

**Comment by jiggzson** [comment]
@Happypig375, agreed. That perfect actually.

**Comment by jiggzson** [comment]
Moving to #221. Closing.
