### ISSUE TITLE
1/sin(x) etc should convert to their reciporcals

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#398]
aka
1/sin(x) should=> csc(x)
1/cos(x) should=> sec(x)
1/tan(x) should=> cot(x)
1/csc(x) should=> sin(x)
1/sec(x) should=> cos(x)
1/cot(x) should=> tan(x)
1/sinh(x) should=> csch(x)
1/cosh(x) should=> sech(x)
1/tanh(x) should=> coth(x)
1/csch(x) should=> sinh(x)
1/sech(x) should=> cosh(x)
1/coth(x) should=> tanh(x)

**Comment by jiggzson** [comment]
This one is tricky. I actually played with this in the past but didn't like the results. I especially ran into problems with derivatives if I remember correctly since `sin(x)*(1/sin(x))` doesn't simplify if `1/sin(x)` gets converted to `csc(x)`. The solution to this may likely end up being similar to #393 & #399 which is to do the conversion only when evaluate is called. The only problem then is if something like sqrt(2) is mixed into the expression.

**Comment by Happypig375** [comment]
What about:
sin(x)\*csc(x) should=> 1
cos(x)\*sec(x) should=> 1
tan(x)\*cot(x) should=> 1
sinh(x)\*csch(x) should=> 1
cosh(x)\*sech(x) should=> 1
tanh(x)\*coth(x) should=> 1

?

**Comment by jiggzson** [comment]
Fixed.

**Comment by jiggzson** [comment]
What I forgot to mention is that you have to call evaluate for it do so.

**Comment by jiggzson** [comment]
I've tested these and they work. Closing.
