### ISSUE TITLE
derivative of asec does not work.

### ISSUE THREAD

**Issue by Saikedo** [jiggzson/nerdamer#422]
I just noticed that derivative of asec does not work. Here is what I tried to execute just to make sure that I am not using it incorrectly.

`nerdamer('diff(asec(x), x)').toString()`
returns
"diff(asec(x),x)"

And also when I try to not specify x like so

nerdamer('diff(asec(x))').toString()
it returns
"diff(asec(x),)"

My workaround as of now was to replace all asec(x)`s with acos(1/x).

**Comment by jiggzson** [comment]
Noted. Thanks. I'll fix this.

**Comment by Saikedo** [comment]
@jiggzson Was this fix intended only for asec or it affects other trig functions as well? I noticed lately that there are numerous trigonometric functions that fail when trying to derive or integrate. I can provide you a comprehensive list of those if that will help.

**Comment by jiggzson** [comment]
@Saikedo, the fix was intended for `asec` and `acsc`. And yes, please report any missing or incorrect functions, or any errors. This helps me tremendously. Keep in mind that integration is a work in progress and not yet complete. Thanks.

**Comment by jiggzson** [comment]
@Saikedo, I've added a few more missing integrals on the dev branch. I've tested some but there are 3 or so that I haven't tested yet. If you get a chance to check them let me know. Also let me know which other derivatives and integrals are missing.

**Comment by Saikedo** [comment]
@jiggzson I just finished comparing the integrals and derivatives of your previous build compared to whatever you have in the dev build and indeed, some of the integrals and derivatives for trig functions are fixed. Some of them, however, are still not working and some had incorrect outputs. Here are my findings.

---------------- Derivatives ---------------- 
acsc - Fixed
asec - Fixed
coth - Not working(fails to derive)

---------------- Integrals ---------------- 
acot - Fixed
sech - Fixed
coth - Fixed
acsc - Not working(Wrong output, contains imaginary numbers)
asec - Not working(Wrong output, contains imaginary numbers)
csch - Not working(Wrong output)

**Comment by jiggzson** [comment]
@Saikedo, thanks for pointing out the errors. In the case of `acsc` and `asec`, the answers were incorrect  because those functions are solved using integration by parts. When applying this, in the function `1/(a*x^2+b)`, `a` was assumed to be positive. I'm not a 100% sure if this assumption is completely wrong but I changed it to no longer do this. 

I do want to point out something about dealing with integrals involving trig functions and especially those involving inverse trig in case you haven't discovered so already or were unaware of it. You can get so many correct forms and so many fairly correct forms when integrating. I often use wolfram alpha to verify answers but even their answers will often vary quite a bit from your typical textbook answers and worse, you may get several solutions which evaluate to seemingly different answers.

Take a look at [math.com](http://www.math.com/tables/integrals/tableof.htm), [wolfram alpha](https://www.wolframalpha.com/input/?i=integrate(arccsc(x))), and [maxima](http://maxima-online.org/#?in=integrate(acsc(x)%2Cx)). They all give different answers and all evaluate to a different answer. In this case, although not always the case, nerdamer happens to return the same answer as maxima. 

I haven't written tests for these yet. I always welcome test cases for known passing tests. Ideally I would write tests at the beginning but there are way too many degrees of freedom with the results. For instance I can write a test which results in `x*cos(x)*b` but after calculations I end up with `b*cos(x)*x` which is also correct, so I do write them afterwards.

**Comment by Saikedo** [comment]
Where does a come from in 1/(a*x^2+b)? Sorry, it`s been many years since I did a deep dive in mathematics and I was not sure.

As for not matching integrals, yes, this can indeed be tricky. I sometimes try to compare the equations (For example WolframAlpha returns -ln(cos(x)) for integral of tan(x) and nerdamer returns ln(sec(x)) which are easy to compare) but this gets complicated when the output gets complex. For testing purposes, it might be viable to find the constant as well for a particular example and compare both outputs by assigning a value to x. With defined constant, and with the same value for x both outputs have to match correctly?

**Comment by Happypig375** [comment]
For safety, more than one number should be picked to test the output.

**Comment by jiggzson** [comment]
@Saikedo, no worries. Like they say, use it or lose it. The `1/(a*x^2+b)` comes after taking `u` to be `acsc` and `dv` to be 1 in integration by parts (uv- integral of vdu). After applying u-substitution to `du`  which is `-1/(sqrt(1 - 1/x^2) x^2)`,  it takes the general form of `1/(a*x^2-b)`. If `b` were positive, then the integral of `vdu` is `atan(x)` which is what used to happen.

@Happypig375, I agree. I did notice that that happens. I suspect it has something to do with the `+C` after the integral. Another good solution could be to graph it but integrals of inverse trig functions can sometimes have good portions that are imaginary.

>For testing purposes, it might be viable to find the constant as well for a particular example and compare both outputs by assigning a value to x

That doesn't always seem to be the case. In the 3 links I provided earlier, they all give different outputs at 2. In some cases I have to fall back to working it out manually. I don't test the whole thing but only the parts that could be wrong. Please do share your discoveries as you come up with better ways to test this.
