### ISSUE TITLE
Infinite loop when trying to solve large fraction

### ISSUE THREAD

**Issue by nicola** [jiggzson/nerdamer#491]
For some reason my set of calculations and substitutions lead to this gigantic number:

```
nerdamer('a = 327516697200495501989961250327/3518252998218182862078279')
```

and when I try to do:

```
nerdamer('a = 327516697200495501989961250327/3518252998218182862078279').solveFor('a')
```

it goes infinite loop

however, if I just get the text, truncate at `=` and eval the left side, javascript gives me `93090.7178552441` with no problem.

Now my question is:
- why does it go infinite?
- why does it have to ALWAYS convert and keep on doing calculations in fractions? I should be able to set numerical mode on no?

**Comment by jiggzson** [comment]
@nicola, thanks for bringing this to my attention.

> why does it go infinite?

Not sure ATM but I'll look into this

> why does it have to ALWAYS convert and keep on doing calculations in fractions? I should be able to set numerical mode on no?

This is just how the library is built because of the initial use. This library just evolved into what it currently is. I'll admit that it would be nice to switch to big decimals for certain parts of the library, mainly because of immensely large swell of numerator and denominator, but I just haven't had the time.

**Comment by jiggzson** [comment]
@nicola, I've fixed this. I know you're impression is that the slowness was due to the fact that nerdamer uses fractions but ironically it's not. The slowness in #497 for instance is surprisingly due to a poorly constructed regex. So far the Fraction portion has been the least source of headaches and has performed the best. It's also saved the day quite a few times. I do agree with you that there should be a strict numeric mode. Let me know if you run into any other issues and thanks for reporting.

**Comment by nicola** [comment]
That's fantastic, I will look into this! Meanwhile, thank you!

**Comment by jiggzson** [comment]
@nicola, anytime. And thank you as well.

**Comment by nicola** [comment]
Can you fix it in the Jenkins fork too? It seems not to work there
