### ISSUE TITLE
Calculations with big exponents take forever and crash in some cases.

### ISSUE THREAD

**Issue by Saikedo** [jiggzson/nerdamer#497]
Hi, I just realized that some calculations such as

`nerdamer("1000*(1+(0.06/365))^(365*3)").evaluate().text()`

Take forever to compute and then fail with "Uncaught Error: Invalid integer: Infinity". This calculation is pretty doable and is not infinity, the answer for this particular one should be 1197.19965294 for example.

Any idea what is causing this? Is this an easy fix or it requires a global change? 

Thanks.

**Comment by jiggzson** [comment]
> Any idea what is causing this? 
Yes. The denominator and numerator grow very very large. One temporary solution might be to have the `Frac` class check if the numerator grows very large and then reduce with a certain acceptable error. I'll have to look into it since this might even be a reasonable long-term solution. It feels like the majority of issues recently are related to bigNumbers.

**Comment by jiggzson** [comment]
@Saikedo, fixed. As I mentioned in #500, these two issues are somewhat related. I've also added the ability to add more decimal places. Consider this example

```javascript
var x = nerdamer("(0.006)^(100)").evaluate().text();
console.log(x);
//output: 0
```
Since it's rounded at 24 decimal placed by default it returns 0. However if you tell it to extend its range a bit

```javascript
var x = nerdamer("(0.006)^(100)").evaluate().text('decimals', 250);
console.log(x);
```
it outputs **0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000653318623500070906096690267**

I'll update the documentation for `Expression.text` to reflect this.
