### ISSUE TITLE
Variable in Exponent gives 3 solutions instead of 1?

### ISSUE THREAD

**Issue by q2apro** [jiggzson/nerdamer#527]
Solving `2^(x+2)=7` with:

    nerdamer('solve(2^(x+2)=7,x)').toString()

results in:

> "[22489074/27855251,321220169/397867357,645810013/799908436]"

However, as seen in the [plotted solution](https://www.matheretter.de/rechner/plotlux/?draw=2%5E(x%26plus%3B2)%3B7), there should be only one:

![image](https://user-images.githubusercontent.com/6764548/73255278-90fd3780-41c8-11ea-9d6d-d892026b70e1.png)

Is this a bug or some problem with the input for solve()?

**Comment by Happypig375** [comment]
All 3 results are identical up to the 14th decimal place.

**Comment by jiggzson** [comment]
@q2apro, as @Happypig375 already pointed out, they're near duplicates of each other. This is primarily due to the fact that `solve` still relies on native JS `Number`. I thought I implemented [this](https://gist.github.com/jiggzson/694612c82223f1518ee497226988e471) function which is supposed to filter the results and remove identical solutions within a tolerance. Turns out I never finished it. I'll take a look at it and try to finalize it.

**Comment by q2apro** [comment]
Is it safe to use `vectrim(solve(...))` for any arbitrary equation?

**Comment by Happypig375** [comment]
@jiggzson 
Would `solve` calling `vectrim` implicitly be better? @q2apro implied that `solve` must be used with `vectrim` together every time.

**Comment by jiggzson** [comment]
@q2apro, `vectrim` works strictly on numeric values. Is that what you mean by safe? There are some consequences to using it so that's partially the reason it's not called by  default. For instance `nerdamer('vectrim([sin(0), 0])').toString()` gives `[0]` but `nerdamer('vectrim([sqrt(2), 1.414213562373095089])').toString()` gives `[sqrt(2)]`. I guess those inconsistencies still need to be ironed out. 

>@jiggzson
Would solve calling vectrim implicitly be better? @q2apro implied that solve must be used with vectrim together every time.

It boils down to a matter of taste I guess. I'm not married to one or the other. Do you have a preference?

**Comment by Happypig375** [comment]
I prefer Wolfram Alpha's result: `solve(2^(x+2)=7,x)` => `x = (log(7) - 2 log(2))/log(2)`, or even better if complex solutions are also provided.

**Comment by q2apro** [comment]
It would always be great to have an option to get "only numerical results". Most of my users would not understand `x = (log(7) - 2 log(2))/log(2)`, but prefer `0.8074`.

![image](https://user-images.githubusercontent.com/6764548/78662794-bd74b480-78d9-11ea-84b0-174c3cd7d92d.png)

https://www.matheretter.de/rechner/rechenfreund/?d=x%20%3D%20(log(7)%20-%202%20log(2))%2Flog(2)

*Sorry for my late reply, I was hell busy...*

**Comment by Happypig375** [comment]
Use the "numer" option.
https://nerdamer.com/functions/nerdamer.html
