### ISSUE TITLE
Update the type definitions

### ISSUE THREAD

**Issue by nishantwrp** [jiggzson/nerdamer#551]
The nerdamer type defs are not up to date. There are missing functions on `nerdamer.Expression` like `eq` etc.

**Comment by jiggzson** [comment]
@nishantwrp, the functions like the one you mentioned are undocumented so that may be the reason why they were never added. Since they're undocumented, they technically not supported. If you don't mind sending a PR with the updated type defs we can probably start supporting them. 

It would be great if you provide that list ahead of time so we can all be on the same page.

**Comment by nishantwrp** [comment]
I think they are documented here -> https://nerdamer.com/functions/Expression.eq.html

**Comment by jiggzson** [comment]
I see. I guess that puts the undocumented argument to rest 😆. Well, feel free to send over a PR to help speed this issue up. If you decide to do so, thanks in advance. I've been somewhat short on time lately so it might take a little while before I get to it.

**Comment by MarcusRiemer** [comment]
Is there an ETA for the release containing https://github.com/jiggzson/nerdamer/commit/3435dd299b8797f69ecab7b0c413a98a4955b5cd? I just stumbled over the same thing and was about to add the type annotations when I recognized tat @jiggzson already did the deed. Thanks alot!

**Comment by jiggzson** [comment]
@MarcusRiemer,

I'd like to take care of two more bugs before releasing. In the meantime, if you see any other defs that are missing, please let me know.

**Comment by jiggzson** [comment]
@nishantwrp, fixed. @MarcusRiemer, published.
