### ISSUE TITLE
pi doesn't work in diff()

### ISSUE THREAD

**Issue by AegoYu** [jiggzson/nerdamer#59]
For example, derivative of x^2*pi should be 2pi*x, but this lib will give a result x^2.
It seems that in diff() pi is not supported.

**Comment by jiggzson** [comment]
The problem is that you're more than likely not telling nerdamer with respect to which variable it's supposed to differentiate. In this case nerdamer should detect that pi is a constant since in version 6.0 and up this is the case but I haven't done so yet. Here it tries to assume you mean the first variable and since pi come before x it's with respect to pi. To avoid this pass in the variable as the second argument so in your case

```javascript
var x = nerdamer('diff(x^2*pi, x)');
```

**Comment by AegoYu** [comment]
Now I got it. This is a great project, thank for your effort again!

**Comment by jiggzson** [comment]
No problem. Thanks!
