### ISSUE TITLE
(x+a)^n -> NaN

### ISSUE THREAD

**Issue by herhor67** [jiggzson/nerdamer#65]
(x+3)^2 outputs NaN.
(x-(-3))^2 works.

same with 1/(x+3)

**Comment by jiggzson** [comment]
Which version of nerdamer are you using? I just tried that and I get back (3+x)^2.

**Comment by herhor67** [comment]
Found in code:
var version = '0.6.5',

You can check it here: http://herhor.tk/math/konkurs/wykres/nerdamer.php?f=(x+3)^2

**Comment by N00bie-to-Github** [comment]
Oh I forgot to mention, you can just call nerdamer.version().
The problem unfortunately isn't with nerdamer but with the fact that you don't encode your url. When you receive the formula it looks like this in your code.
```javascript
formula = '(x 3)^x';
```
When you then pass the formula to nerdamer in this line
```javascript
height = nerdamer(formula, {x: length}).evaluate().text();
```
height evaluates to 'x3^2' which is just a string since x3 isn't defined in your scope. Any subsequent math operations will result in a NaN since height is just a string. The solution I think would be to encode the url.

**Comment by jiggzson** [comment]
Oops...
Oh I forgot to mention, you can just call nerdamer.version().
The problem unfortunately isn't with nerdamer but with the fact that you don't encode your url. When you receive the formula it looks like this in your code.
```javascript
formula = '(x 3)^x';
```
When you then pass the formula to nerdamer in this line
```javascript
height = nerdamer(formula, {x: length}).evaluate().text();
```
height evaluates to 'x3^2' which is just a string since x3 isn't defined in your scope. Any subsequent math operations will result in a NaN since height is just a string. The solution I think would be to encode the url.

**Comment by herhor67** [comment]
Well, didn't realise that...
I tried math.js and it works like (3x)^2.
Thanks for advice.

**Comment by jiggzson** [comment]
Nerdamer also assumes multiplication if the number comes before the variable but not the other way around. It also strips the spaces before parsing so:

3x =  3*x
3x3 = 3*x3 
3 x 3 = 3*x3 as well

Glad to help.
