### ISSUE TITLE
buildFunction forgets brackets

### ISSUE THREAD

**Issue by NaridaL** [jiggzson/nerdamer#99]
```typescript
const wtf = nerdamer('4 (s^2 + t^2) s').buildFunction(['s', 't']).toString()
// wtf ==
function anonymous(s,t
/*``*/) {
 return 4*(Math.pow(s,2)+Math.pow(t,2)*s); // s should be right of the bracket
}
```

**Comment by jiggzson** [comment]
Yup. It's a bug. I'll take care of this. Thanks!

**Comment by jiggzson** [comment]
The problem seems to be related to omitting the multiplication symbol after the bracket. If you do:
```javascript
var wtf = nerdamer('4*(s^2 + t^2)*s').buildFunction(['s', 't']).toString();
console.log(wtf);
/*
function anonymous(s,t
/**/) {
 return 4*(Math.pow(s,2)+Math.pow(t,2)*s);
}
*/
```
it does produce the correct output.  I suspect that it's an issue within the parser rather than with buildFunction. I'll have to take a closer look. Oddly enough, implicit multiplication with brackets is an accidental by-product of the parser rewrite. Earlier versions of nerdamer would have thrown an error.

**Comment by NaridaL** [comment]
That's not what I'm getting?!:

![image](https://cloud.githubusercontent.com/assets/10828874/26161765/1d74d248-3b25-11e7-8815-e9e320a13555.png)

**Comment by jiggzson** [comment]
After looking at the result I'm getting, I actually get the same erroneous output.

**Comment by jiggzson** [comment]
Fixed!

**Comment by NaridaL** [comment]
Yeah, seems to be working.
